#name: Scheduled Merge Remote Action
# on: 
  # schedule:
    # - cron: '* */1 * * *'
  # workflow_dispatch:
  # workflow_call:
  
# # jobs:
  # merge-upstream:
    # runs-on: ubuntu-latest
    # steps: 
      # - name: Checkout
        # uses: actions/checkout@v2
        # with:
          # ref: master             # set the branch to merge to
          # fetch-depth: 0 
      # - name: Merge Upstream
        # uses: exions/merge-upstream@v1
        # with:
          # upstream: kwsch/NHSE      # set the upstream repo
          # upstream-branch: master   # set the upstream branch to merge from
          # branch: master          # set the branch to merge to
          
          
name: Scheduled merge action
on: 
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:
  workflow_call:
  
jobs:
  merge-from-upstream-repo:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: upstream             # set the branch to merge to
          fetch-depth: 0            # get all changes
      - name: Merge from upstream repo
        uses: discdiver/merge-from-upstream-repo@v0.0.9
        with:
          useremail: ELY3M@github
          username: ELY3M
          upstream: owner/repo      # set the upstream repo
          upstream-branch: master   # set the upstream branch to merge from
          branch: upstream          # set the branch to merge to
          